[package]
name = "mega_etl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
mysql_async_wasi = "0.30"
thiserror = "1.0"
url = "2.3.1"